### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Anand-S23** [Anand-S23/Frame#1]
Update the README to give better insight into the project on the following areas:
- Layout features that will be in the final project
- Getting the project bootstrapped locally
- The status for the development of different features

### TODO:
- [x] Add todo/features area that goes over what has been done and needs to be done
- [x] a quick start section that gets new developer up and running with the project local
- [x] an architecture section which breaks down the tech that is used project and overall design of the project
