### ISSUE TITLE
Authentication: Update Register Fields

### ISSUE THREAD

**Issue by Anand-S23** [Anand-S23/Frame#11]
The platform with a 13+ platform, and should require a DOB to verify this. 

### TODO: 
- [ ] Add DOB field to models
- [ ] Update existing register logic + validation to include DOB
- [ ] Add DOB input + validation on frontend
