### ISSUE TITLE
Authentication: Register

### ISSUE THREAD

**Issue by Anand-S23** [Anand-S23/Frame#3]
Create frontend form to register a user to website.

### TODO:
- [x] Create register form component
- [x] Use react-form-hook to handle form state
- [x] Call the `/register` endpoint in the to add user to database
- [x] Use Zod to handle register data
- [x] Display proper error message, if error occurs
