### ISSUE TITLE
Authentication: Login

### ISSUE THREAD

**Issue by Anand-S23** [Anand-S23/Frame#4]
Create frontend form to login a user to website.

### TODO:
- [x] Create login form component
- [x] Use react-form-hook to handle form state
- [x] Call the `/login` endpoint in the to add user to database
- [x] Use Zod to handle register data
- [x] Display proper error message, if error occurs
