### ISSUE TITLE
Authentication: OAuth

### ISSUE THREAD

**Issue by Anand-S23** [Anand-S23/Frame#9]
Add Google login via OAuth.

### TODO:
- [ ] Add controllers for handling Google OAuth login/register
- [ ] Update User model as needed to add OAuth support
- [ ] Create routes for Google OAuth login/register
- [ ] Add the ability in the frontend to login/register with Google
- [ ] Verify the jwt portion of the app still works as expected and did not break due to this
